add_library(simlang STATIC)

target_sources(simlang PRIVATE
        ast/assignmentop.h
        ast/astcloner.h
        ast/astvisitorbase.h
        ast/astwalker.h
        ast/binaryop.h
        ast/exprutils.cpp
        ast/exprutils.h
        ast/nodes/astnode.h
        ast/nodes/exprnodes.h
        ast/nodes/nodetypes.def
        ast/nodes/nodetypes.h
        ast/nodes/paramnodes.h
        ast/nodes/stmtnodes.h
        ast/nodes/translationunitnode.h
        ast/nodes/typespecifiernodes.h
        ast/unaryop.h
        backend/backendstate.cpp
        backend/backendstate.h
        backend/bytecode/bytecodeanalyzer.cpp
        backend/bytecode/bytecodeanalyzer.h
        backend/bytecode/bytecodebuilder.h
        backend/bytecode/bytecodecfg.cpp
        backend/bytecode/bytecodecfg.h
        backend/bytecode/bytecodedump.cpp
        backend/bytecode/bytecodedump.h
        backend/bytecode/bytecodedumpoptions.h
        backend/bytecode/bytecodeemitter.cpp
        backend/bytecode/bytecodeemitter.h
        backend/bytecode/bytecodeprogram.h
        backend/bytecode/optimizer.cpp
        backend/bytecode/optimizer.h
        backend/codegen/codegenvisitor.cpp
        backend/codegen/codegenvisitor.h
        backend/codegen/codegenvisitorbool.cpp
        backend/codegen/codegenvisitorcall.cpp
        backend/codegen/codegenvisitorconstruct.cpp
        backend/codegen/codegenvisitorexpr.cpp
        backend/codegen/codegenvisitorlvalue.cpp
        backend/codegen/codegenvisitorops.cpp
        backend/codegen/codegenvisitorstmt.cpp
        backend/codegen/place.cpp
        backend/codegen/place.h
        backend/layout/aggregatelayoutvisitor.cpp
        backend/layout/aggregatelayoutvisitor.h
        backend/layout/constdatalayoutvisitor.cpp
        backend/layout/constdatalayoutvisitor.h
        backend/layout/layout.cpp
        backend/layout/layout.h
        backend/layout/symbollayoutvisitor.cpp
        backend/layout/symbollayoutvisitor.h
        backend/layout/typelayouttablebuilder.cpp
        backend/layout/typelayouttablebuilder.h
        backend/layout/typelayouttablevisitor.cpp
        backend/layout/typelayouttablevisitor.h
        backend/stringdata.cpp
        backend/stringdata.h
        backend/typeidutils.cpp
        backend/typeidutils.h
        compiler.cpp
        compiler.h
        compileroptions.h
        diag/diagnostic.h
        diag/diagnosticformat.h
        diag/diagnosticinfo.h
        diag/diagnosticlevel.h
        diag/diagnosticmanager.cpp
        diag/diagnosticmanager.h
        diag/diagnostics.def
        diag/diagnostictype.h
        driver/backenddriver.cpp
        driver/backenddriver.h
        driver/compilerlog.cpp
        driver/compilerlog.h
        driver/compilercontext.h
        driver/frontenddriver.cpp
        driver/frontenddriver.h
        driver/phaselogger.cpp
        driver/phaselogger.h
        module/moduledata.h
        module/moduleentry.h
        module/modulemanager.cpp
        module/modulemanager.h
        module/modulestage.h
        parser/parser.h
        parser/parsercontext.h
        parser/parsercore.cpp
        parser/parserexpr.cpp
        parser/parserstmt.cpp
        parser/parsertoplevel.cpp
        parser/parsertypes.cpp
        parser/token.h
        parser/tokenizer.cpp
        parser/tokenizer.h
        parser/tokentype.h
        parser/tokentypes.def
        runtime/callinfo.h
        runtime/executableimage.h
        runtime/memory/heapblock.h
        runtime/memory/heap.cpp
        runtime/memory/heap.h
        runtime/memory/typelayout.h
        runtime/memory/typelayouttable.h
        runtime/op/op.h
        runtime/op/opmacros.h
        runtime/op/opcode.h
        runtime/op/opcodes.def
        runtime/op/oputils.cpp
        runtime/op/oputils.h
        runtime/runtimedebuginfo.cpp
        runtime/runtimedebuginfo.h
        runtime/runtimeerror.h
        runtime/runtimeerrorsink.cpp
        runtime/runtimeerrorsink.h
        runtime/stringdata.h
        runtime/typeids.h
        runtime/syscall/nativetype.h
        runtime/syscall/syscallentry.h
        runtime/syscall/syscaller.h
        runtime/syscall/syscallregistry.cpp
        runtime/syscall/syscallregistry.h
        runtime/syscall/syscalltypes.h
        runtime/vm/vm.cpp
        runtime/vm/vm.h
        runtime/vm/vmstack.cpp
        runtime/vm/vmstack.h
        runtime/vmdefines.h
        sema/passes/constevalvisitor.cpp
        sema/passes/constevalvisitor.h
        sema/passes/constfoldvisitor.cpp
        sema/passes/constfoldvisitor.h
        sema/passes/declcollectorvisitor.cpp
        sema/passes/declcollectorvisitor.h
        sema/passes/importvisitor.cpp
        sema/passes/importvisitor.h
        sema/passes/resolutionvisitor.cpp
        sema/passes/resolutionvisitor.h
        sema/passes/implicitthisvisitor.cpp
        sema/passes/implicitthisvisitor.h
        sema/passes/typecheckvisitor.cpp
        sema/passes/typecheckvisitor.h
        sema/passes/typecheckvisitoraggregate.cpp
        sema/passes/typecheckvisitorexpr.cpp
        sema/passes/typecheckvisitorops.cpp
        sema/passes/typecheckvisitorresolve.cpp
        sema/passes/typecheckvisitorstmt.cpp
        sema/scopes.cpp
        sema/scopes.h
        sema/templateinstantiationcache.h
        sema/templateinstantiator.cpp
        sema/templateinstantiator.h
        source/linecolumninfo.h
        source/source.cpp
        source/source.h
        source/sourcelocation.h
        source/sourcemanager.cpp
        source/sourcemanager.h
        source/sourcerange.h
        symbol/constvalue.cpp
        symbol/constvalue.h
        symbol/identifier.h
        symbol/identifiertable.cpp
        symbol/identifiertable.h
        symbol/interning.h
        symbol/internedstring.h
        symbol/stringtable.cpp
        symbol/stringtable.h
        symbol/symbol.h
        symbol/symbolregistry.cpp
        symbol/symbolregistry.h
        symbol/symboltype.h
        symbol/symbolutils.h
        type/typeformat.cpp
        type/typeformat.h
        type/typekind.h
        type/types.h
        type/typetable.cpp
        type/typetable.h
        util/arena.cpp
        util/arena.h
        util/arenautils.h
        util/arrayview.h
        util/asserts.cpp
        util/asserts.h
        util/bitutils.h
        util/escaping.cpp
        util/escaping.h
        util/flags.h
        util/meta.h
        util/numeric.h
        util/scoping.h
        util/textsink.h
        util/textsinks.h
        util/textwriter.cpp
        util/textwriter.h
        util/types.h
)

target_include_directories(simlang PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})

target_compile_features(simlang PUBLIC cxx_std_17)

target_link_libraries(simlang PRIVATE simlang_options)
